Travel/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from first import views

urlpatterns = [
    path('',views.index,name='index'),
    path('users/',views.users,name='users'),
    path('first/',include('first.urls')),
    path('admin/', admin.site.urls),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/urls.py
from django.urls import path
from first import views

app_name = 'first'

urlpatterns = [
            path('contact/',views.contact,name='contact'),
            path('itenary/',views.itenary,name='itenary'),
            path('gallery/',views.gallery,name='gallery'),
            path('faq/',views.faq,name='faq'),
            path('about/',views.about,name='about'),
            path('annapurna/',views.annapurna,name='annapurna'),
            path('langtang/',views.langtang,name='langtang'),
            path('annapurnacircuit/',views.annapurnacircuit,name='annapurnacircuit'),
            path('poonhill/',views.poonhill,name='poonhill'),
            path('mardihimal/',views.mardihimal,name='mardihimal'),
            path('everestthreepasses/',views.everestthreepasses,name='everestthreepasses'),
]

first/models.py
from django.db import models

# Create your models here.
class Form(models.Model):
    Name = models.CharField(max_length=255)
    Email = models.CharField(max_length=255)
    Country = models.CharField(max_length=255, default=0)
    Comment = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.Email

class Feedback(models.Model):
    Name = models.CharField(max_length=255)
    feedback = models.TextField(blank=True,null=True)
    Archived = models.BooleanField(default=False)

    def __str__(self):
        return self.Name

class GalleryImage(models.Model):
    HoverTitle = models.CharField(max_length=255)
    PicTitle = models.CharField(max_length=255)
    Image = models.ImageField(upload_to='gallery_pics/')

    def __str__(self):
        return self.PicTitle

class Information_slide(models.Model):
    Title = models.CharField(max_length=255)
    latest_news = models.CharField(max_length=255)
    
    def __str__(self):
        return self.Title

first/forms.py
from django import forms


# class forminput(forms.ModelForm):
#     class Meta():
#         model = Form
#         fields = '__all__'





# class FormName(forms.Form):
#     Name = forms.CharField()
#     Email = forms.EmailField()
#     Comment = form.CharField(widget=forms.Textarea)
    # botcatcher =forms.CharField(required=False, widget=forms.HiddenInput)

first/views.py
from django.shortcuts import render
from django.contrib import messages
from django.core.mail import send_mail
from .models import Form,Feedback,GalleryImage,Information_slide

# from first import forms
# from first.forms import forminput
# Create your views here.

def index(request):
    testi = Feedback.objects.all().order_by('-id')
    info_slid = Information_slide.objects.all().order_by('-id')
    # testi = Feedback.objects.filter(archived=False).order_by('id') [('-id')]=pixadibata 
    context ={"testi":testi,"info_slid":info_slid}
    return render(request, 'first/index.html', context)

def users(request):
    if request.method == 'POST':
        if request.POST.get('name') and request.POST.get('email'):
            post=Form()

            post.Name = request.POST.get('name')
            post.Email = request.POST.get('email')
            post.Country = request.POST.get('country')
            post.Comment = request.POST.get('message')

            post.save()

            # send_mail(
            # post.Name + 'from' + post.Country,#subject
            # post.Comment,  #message
            # post.Email,  #from email
            # ['rabidarkers@gmail.com'],#to email -> this is python list ['email','2ndemail'] 'travelfeet.np@gmail.com',
            # )


            return render(request,'first/contact_main.html', {'post_Name': post.Name})
            # return index(request)
            # else:
            #     return index("Fill Valid Information")
        else:
            return render(request,'first/index.html')

        #send an email
        # message_name = request.POST['name']
        # message_email = request.POST['email']
        # message_country = request.POST['country']
        # message_comment = request.POST['message']
        # send_mail(
        #     message_name + 'from' + message_country,#subject
        #     message_comment,  #message
        #     message_email,  #from email
        #     ['travelfeet.np@gmail.com'],#to email -> this is python list ['email','2ndemail']
        # )



def contact(request):
    return render(request, 'first/contact_main.html')

def gallery(request):
    galler = GalleryImage.objects.all().order_by('-id')
    context = {"galler":galler}
    return render(request, 'first/gallery_main.html', context)

def itenary(request):
    return render(request, 'first/itenary_main.html')

def faq(request):
    return render(request, 'first/faq_main.html')

def about(request):
    return render(request, 'first/about_main.html')


# itinary 


def annapurna(request):
    return render(request, 'first/itinaryfiles/annapurna.html')

def langtang(request):
    return render(request, 'first/itinaryfiles/langtang.html')

def annapurnacircuit(request):
    return render(request, 'first/itinaryfiles/annapurnacircuit.html')

def poonhill(request):
    return render(request, 'first/itinaryfiles/poonhill.html')    

def mardihimal(request):
    return render(request, 'first/itinaryfiles/mardihimal.html')   

def everestthreepasses(request):
    return render(request, 'first/itinaryfiles/everestthreepasses.html') 

templates/first/about_main.html
{% extends 'first/menu.html' %}
{% load static %}
{% block title %}About Us{% endblock %}
{% block body_block %}

<section class="aboutus js--section-about" id="about" style="background-color: #e6e4e4;">
    <div class="row">
        <h2>About Us</h2>
        <p class="long-copy">
            Company Overview: <br>
            In the country of legendary old cultural heritages, tremendous hospitality, independent and peace loving
            people, hypnotizing natural beauty and silver shining mountains, we feel proud in providing you a well
            organised, comfortable and connected Travel services and facilities. Our main aim is to Promote National
            as well as International Tourism with the main motto of,
            Habitat, Health and Humanity and a Slogan "Allow your feet to Travel" "GO GREEN, GO DIGITAL"<br>
    
            
                How was Travelfeet Nepal formed? <br>
                The first initiative was to start a photography page having the vision to highlight the underrated
                destinations of Nepal and to reflect the cultural, geographical, natural and archaeological
                diversity of
                Nepal through lens. Passion and dedication are factors that drive people to do more in specific
                field.
                The hunger to deliver Quality contents made us enthusiastic travelers that helped us grow our
                knowledge
                and experience in the field of Travel and Tourism.
                We started realizing the opportunities and platform of Tourism in this mesmerizing country full of
                Beauty. We analyzed that we were having a strong foundation to move forward. We started growing up
                tons
                of good ideas. <br>
                <br>
                We had a team so following were the questions that we asked ourselves. <br>
    
                • What skills do we have?<br>
                • Where does our passion lie?<br>
                • Where is our area of expertise?<br>
                • How much can we afford to spend, knowing that most businesses fail?<br>
                • How much capital do we need?<br>
                • What sort of lifestyle we want to live?<br>
                • Are we even ready to be an entrepreneur?<br>
                <br>
                Everything starts as a dream. We knew that initiation and implementation make Dream work. We had
                nothing
                to lose and we all were passionate to work but mainly we had a positive clear answers for all of the
                questions. A dream to be one of the best Travel Company representing Nepal formed Travelfeet Nepal
                with
                a motto “Allow your feet to Travel”.
                Travelfeet Nepal is a Certified Travel Company, a team of young and energetic students pursuing the
                Bachlors in Travel and Tourism (BTTM) and Bachlors in Information Technology (BIT). <br>
                <br>
                What do we do?<br>
                • Tours <br>
                • Trekking <br>
                • Adventure <br>
                • Internship <br>
                • Vehicle Rental <br>
                • Accommodation <br>
                • Air Ticket <br>
                • Photography/Videography Projects <br>
            
        </p>
    </div>
    </section>

{% endblock %}
   

templates/first/contact_main.html
{% extends 'first/menu.html' %}
{% load static %}
{% block title %}Contact Us{% endblock %}
{% block body_block %}
{% include 'first/contact_base.html' %}

{% endblock %}

templates/first/gallery_main.html
{% extends 'first/menu.html' %}
{% load static %}
{% block title %}Gallery{% endblock %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'css/gal_css/lightbox.min.css' %}">
<script src="{% static 'js/gal_js/lightbox-plus-jquery.min.js' %}"></script>
<link  href="{% static 'js/gal_js/lightbox-plus-jquery.min.map' %}">
<style>
  .rows {
    /* display: -ms-flexbox;*/
    display: flex;
    /* -ms-flex-wrap: wrap; */
    flex-wrap: wrap;
    /*padding: 0 10px;*/
    
  }
  
  /* Create four equal columns that sits next to each other */
  .columns {
    /* -ms-flex: 33.3%; */
    flex: 33.3%;
    padding: 0px;
  }

  .columns a img{
    vertical-align: middle;
    /*width: 100%;*/
    height : 300px;
  }
  .columns a img:hover,
  .columns a img:active {
    opacity: 100%;
    transform: scale(0.95);
     /* transform: scale(0.95); */
      transition: transform 0.3s, opacity 0.3s; 
  }
  
  /* Responsive layout - makes a two column-layout instead of four columns */
  @media screen and (max-width: 800px) {
    .columns {
      -ms-flex: 50%;
      flex: 50%;
      max-width: 50%;
    }
  }
  
  /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
  @media screen and (max-width: 600px) {
    .columns {
      -ms-flex: 100%;
      flex: 100%;
      max-width: 100%;
    }
  }

</style>

<section style="background-color: #e6e4e4;padding-bottom: 10px;">
  
  <h2>Gallery</h2>
  
  <div class="rows js--section-about">  
  {% for galls in galler %}
        <div class="columns">
          <div class='gul'>
          <a href="{{galls.Image.url}}" data-lightbox="mygallery" data-title="{{galls.PicTitle}}">
          <img src="{{galls.Image.url}}" title="{{galls.HoverTitle}}" style="width:100%" alt="{{galls.HoverTitle}}">
          </a>
          </div>
        </div>
  {% endfor %}
  </div>
</section>

{% endblock %}

templates/first/index_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static '/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/grid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/ionicons.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/queries.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap" rel="stylesheet" type="text/css">

    <title>
    {% block title %}
    TravelFeetNepal
    {% endblock %}
    </title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    
    <link rel="stylesheet" href="{% static '/css/contact.css' %}">
    <link rel="stylesheet" href="{% static '/css/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static '/css/slick/slick-theme.css' %}">
</head>
<body>
    <header>
        <nav>
            <div class="row">
              <a href="{% url 'index' %}">
                <img src="{% static 'img/rst.png' %}" alt="TravelFeetNepal" class="logo">
                  <img src="{% static 'img/rst.png' %}" alt="TravelFeetNepal" class="logo-black">
                </a>

                <ul class="main-nav js--main-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="#about">About Us</a></li>
                    <li><a href="{% url 'first:itenary' %}">Trips</a></li>
                    <li><a href="{% url 'first:gallery' %}">Gallery</a></li>
                    <li><a href="{% url 'first:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'first:faq' %}">FAQ</a></li>
                </ul>
                <a class="mobile-nav-icon js--nav-icon"> <ion-icon name="menu" class="responsive-nav-icon"></ion-icon></a>
            </div>
        </nav>
        
        <div class="marquee">
            <div class="inner">
              <p style="font-size:15px;letter-spacing: 4px;">TravelFeetNepal:Allow Your Feet To Travel&nbsp;&nbsp;|&nbsp;&nbsp;
                {% for info_slider in info_slid %}
                {{info_slider.latest_news}}&nbsp;&nbsp;|&nbsp;&nbsp;
                {% endfor %}
                
            </div>
        </div>
        <script
    src="https://code.jquery.com/jquery-2.0.2.min.js"
    integrity="sha256-TZWGoHXwgqBP1AF4SZxHIBKzUdtMGk0hCQegiR99itk="
    crossorigin="anonymous"></script>
        <script>
            
function handleMarquee() {
    const marquee = document.querySelectorAll('.marquee');
    let speed = 1;
    let lastScrollPos = 0;
    let timer;
    marquee.forEach(function(el) {
      const container = el.querySelector('.inner');
      const content = el.querySelector('.inner > *');
      //Get total width
      const elWidth = content.offsetWidth;
      //Duplicate content
      let clone = content.cloneNode(true);
      container.appendChild(clone);
      let progress = 1;
      function loop() {
        progress = progress - speed;
        if(progress <= elWidth * -1) {
          progress = 0;
        }
        container.style.transform = 'translateX(' + progress + 'px)';
        container.style.transform += 'skewX(' + speed * 0.4 + 'deg)';
        window.requestAnimationFrame(loop);
      }
      loop();
    });
    window.addEventListener('scroll', function() {
      const maxScrollValue = 12;
      const newScrollPos = window.scrollY;
      let scrollValue = newScrollPos - lastScrollPos;
      if(scrollValue > maxScrollValue) scrollValue = maxScrollValue;
      else if(scrollValue < -maxScrollValue) scrollValue = -maxScrollValue;
      speed = scrollValue;
      clearTimeout(timer);
      timer = setTimeout(handleSpeedClear, 10);
    });
    function handleSpeedClear() {
      speed = 1;
    }
  };
  handleMarquee();
        </script>
    </header>
    
{% block body_block %}
{% endblock %}
<footer class="footer-distributed">
    <div class="footer-left">
        <a href="{% url 'index' %}">
            <img src="{% static 'img/rst.png' %}" alt="TravelFeetNepal">
            <h3 style="font-family:'Lato', 'Arial', sans-serif;;">TravelFeet Nepal</h3>
        </a>
        <p class="footer-company-name">© 2020 By TravelFeetNepal. All rights reserved.</p>
    </div>

    <div class="footer-center">
        <div>
            <ion-icon name="location-sharp" class="footer-location"></ion-icon>
              <p><span>Sorakhutte, Thamel
                 </span>
                Kathmandu,Nepal</p>
        </div>
        <br>
        <div>
            <ion-icon name="call-sharp" class="footer-call"></ion-icon>
            <p>+91 22-27782183</p>
        </div>
        <br>
        <div>
            <ion-icon name="mail-sharp" class="footer-mail"></ion-icon>
            <p><a href="mailto:support@eduonix.com"> support@eduonix.com</a></p>
        </div> 
    </div>

    <div class="footer-right">
        <p class="footer-company-about">
            <span>About the company</span>
            We offer training and skill building courses across Technology, Design, Management, Science and Humanities.</p>
        <div class="footer-icons">
            <a href="#"><ion-icon name="logo-facebook" class="ion-facebook"></ion-icon></a>
            <a href="#"><ion-icon name="logo-twitter" class="ion-twitter"></ion-icon></a>
            <a href="#"><ion-icon name="logo-instagram" class="ion-instagram"></ion-icon></a>
            <a href="#"><ion-icon name="logo-linkedin" class="ion-linkedin"></ion-icon></a>
        </div>
    </div>
    <br>
</footer>

    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/waypoints/jquery.waypoints.min.js' %}"></script>
    
    <script src="{% static 'js/script.js' %}"></script>

    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

    <script src="{% static 'js/slick/slick.js' %}"></script>

    

  </body>
</html>

templates/first/itenary_main.html
{% extends 'first/menu.html' %}
{% load static %}
{% block title %}Trips{% endblock %}
{% block body_block %}

<section class="visits  js--section-about" style="background-color: #e6e4e4;">
    <div class="row">
        <h2>Trips</h2>
    </div>
    <div class="row">
    <div class="col span-1-of-3 box">
        <a href="{% url 'first:annapurna' %}"><img src="{% static 'img/it1.jpg' %}" alt="annapurna"> <h3>Annapurna Base Camp</h3> </a>
        
    </div>

    <div class="col span-1-of-3 box">
        <a href="{% url 'first:langtang' %}"><img src="{% static 'img/it2.jpg' %}" alt="langtang"><h3>Langtang Valley</h3></a>
        
    </div>

    <div class="col span-1-of-3 box">
        <a href="{% url 'first:annapurnacircuit' %}"><img src="{% static 'img/it3.jpg' %}" alt="annapurna"><h3>Annapurna Circuit</h3></a>
        
    </div>
</div>
<div class="row">
    <div class="col span-1-of-3 box">
        <a href="{% url 'first:poonhill' %}"><img src="{% static 'img/it2.jpg' %}" alt="poonhill"><h3>Poonhill</h3></a>
        
    </div>

    <div class="col span-1-of-3 box">
        <a href="{% url 'first:mardihimal' %}"><img src="{% static 'img/it1.jpg' %}" alt="mardihimal"><h3>Mardi Himal</h3></a>
       
    </div>

    <div class="col span-1-of-3 box">
        <a href="{% url 'first:everestthreepasses' %}"><img src="{% static 'img/it3.jpg' %}" alt="Everest"><h3>Everest Three High Passes</h3></a>
        
    </div>
</div>

<!-- from here not done -->

    <!-- <div class="row">
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it2.jpg' %}" alt="Lisbon"><h3>Lisbon</h3></a>
            
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it1.jpg' %}" alt="San Francisco"><h3>Lisbon</h3></a>
           
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it3.jpg' %}" alt="Berlin"><h3>Lisbon</h3></a>
            
        </div>
    </div>

    <div class="row">
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it2.jpg' %}" alt="Lisbon"><h3>Lisbon</h3></a>
            
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it1.jpg' %}" alt="San Francisco"><h3>Lisbon</h3></a>
           
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it3.jpg' %}" alt="Berlin"><h3>Lisbon</h3></a>
            
        </div>
    </div>

    <div class="row">
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it2.jpg' %}" alt="Lisbon"><h3>Lisbon</h3></a>
            
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it1.jpg' %}" alt="San Francisco"><h3>Lisbon</h3></a>
           
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it3.jpg' %}" alt="Berlin"><h3>Lisbon</h3></a>
            
        </div>
    </div>

    <div class="row">
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it2.jpg' %}" alt="Lisbon"><h3>Lisbon</h3></a>
            
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it1.jpg' %}" alt="San Francisco"><h3>Lisbon</h3></a>
           
        </div>
    
        <div class="col span-1-of-3 box">
            <a href="#"><img src="{% static 'img/it3.jpg' %}" alt="Berlin"><h3>Lisbon</h3></a>
            
        </div>
    </div> -->
    
    </section>

{% endblock %}
   

templates/first/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static '/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/grid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/ionicons.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/queries.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap" rel="stylesheet" type="text/css">

    <title>
    {% block title %}
    TravelFeetNepal
    {% endblock %}
    </title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="stylesheet" href="{% static 'css/itinarycss/annapurna.css' %}">

    <link rel="stylesheet" href="{% static '/css/contact.css' %}">
    
</head>
<body>
    <header>
        <nav>
            <div class="row">
              <a href="{% url 'index' %}">
                <img src="{% static 'img/rst.png' %}" alt="TravelFeetNepal" class="logo">
                  <img src="{% static 'img/rst.png' %}" alt="TravelFeetNepal" class="logo-black">
                </a>

                <ul class="main-nav js--main-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'first:about' %}">About Us</a></li>
                    <li><a href="{% url 'first:itenary' %}">Trips</a></li>
                    <li><a href="{% url 'first:gallery' %}">Gallery</a></li>
                    <li><a href="{% url 'first:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'first:faq' %}">FAQ</a></li>
                </ul>
                <a class="mobile-nav-icon js--nav-icon"> <ion-icon name="menu" class="responsive-nav-icon"></ion-icon></a>
            </div>
        </nav>
    </header>
{% block body_block %}
{% endblock %}
<footer class="footer-distributed">
    <div class="footer-left">
        <a href="{% url 'index' %}">
            <img src="{% static 'img/rst.png' %}" alt="TravelFeetNepal">
            <h3 style="font-family:'Lato', 'Arial', sans-serif;;">TravelFeet Nepal</h3>
        </a>
        <p class="footer-company-name">© 2020 By TravelFeetNepal. All rights reserved.</p>
    </div>

    <div class="footer-center">
        <div>
            <ion-icon name="location-sharp" class="footer-location"></ion-icon>
              <p><span>Sorakhutte, Thamel
                 </span>
                Kathmandu,Nepal</p>
        </div>
        <br>
        <div>
            <ion-icon name="call-sharp" class="footer-call"></ion-icon>
            <p>+91 22-27782183</p>
        </div>
        <br>
        <div>
            <ion-icon name="mail-sharp" class="footer-mail"></ion-icon>
            <p><a href="mailto:support@eduonix.com"> support@eduonix.com</a></p>
        </div> 
    </div>
    <div class="footer-right">
        <p class="footer-company-about">
            <span>About the company</span>
            We offer training and skill building courses across Technology, Design, Management, Science and Humanities.</p>
        <div class="footer-icons">
            <a href="#"><ion-icon name="logo-facebook" class="ion-facebook"></ion-icon></a>
            <a href="#"><ion-icon name="logo-twitter" class="ion-twitter"></ion-icon></a>
            <a href="#"><ion-icon name="logo-instagram" class="ion-instagram"></ion-icon></a>
            <a href="#"><ion-icon name="logo-linkedin" class="ion-linkedin"></ion-icon></a>
        </div>
    </div>
    <br>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static '/js/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static '/js/script.js' %}"></script>

<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>


</body>
</html>